---
theme: jekyll-theme-cayman

title: [Abhishek Naik]
description: [Has the mind of a techie and the heart of a wanderer.]

social_links:
  github: "https://github.com/abhisheknaik96/"
  twitter: "https://twitter.com/anaik96"
  linkedin: "https://linkedin.com/in/abhisheknaik96"
  goodreads: "https://www.goodreads.com/user/show/41821528-abhishek-naik"
---